/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BranchCreateRequestDto,
  GetMessagesByLinearChatIdParams,
  GraphChatCreateRequestDto,
  GraphChatRenameRequestDto,
  LinearChatCreateRequestDto,
  MessageCreateRequestDto,
  ServiceLoginRequestDto
} from './dto';

import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  GraphChatCreateResponseDto,
  GraphChatResponseDto,
  GraphChatShortResponseDto,
  LinearChatResponseDto,
  MessageCreateResponseDto,
  MessageGraphDto,
  MessageResponseDto,
  MessagesPageResponseDto,
  MqttAuthTokenResponse,
  UserDataResponseDto,
  UserIdResponseDto
} from './dto';

import { restApiAxiosClient } from './restApiAxiosClient';
/**
 * Сохраняет сообщение пользователя в существующую ветку и инициирует асинхронную генерацию ответа ИИ
 * @summary Отправить сообщение
 */
export const sendMessageToExistingLinearChat = (
    messageCreateRequestDto: MessageCreateRequestDto,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<MessageCreateResponseDto>(
      {url: `/messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: messageCreateRequestDto, signal
    },
      );
    }
  


export const getSendMessageToExistingLinearChatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendMessageToExistingLinearChat>>, TError,{data: MessageCreateRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof sendMessageToExistingLinearChat>>, TError,{data: MessageCreateRequestDto}, TContext> => {

const mutationKey = ['sendMessageToExistingLinearChat'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendMessageToExistingLinearChat>>, {data: MessageCreateRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  sendMessageToExistingLinearChat(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendMessageToExistingLinearChatMutationResult = NonNullable<Awaited<ReturnType<typeof sendMessageToExistingLinearChat>>>
    export type SendMessageToExistingLinearChatMutationBody = MessageCreateRequestDto
    export type SendMessageToExistingLinearChatMutationError = unknown

    /**
 * @summary Отправить сообщение
 */
export const useSendMessageToExistingLinearChat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendMessageToExistingLinearChat>>, TError,{data: MessageCreateRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendMessageToExistingLinearChat>>,
        TError,
        {data: MessageCreateRequestDto},
        TContext
      > => {

      const mutationOptions = getSendMessageToExistingLinearChatMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Создает новый линейный чат в рамках графового чата
 * @summary Создать новый линейный чат
 */
export const createLinearChat = (
    linearChatCreateRequestDto: LinearChatCreateRequestDto,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<LinearChatResponseDto>(
      {url: `/linear-chats`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: linearChatCreateRequestDto, signal
    },
      );
    }
  


export const getCreateLinearChatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLinearChat>>, TError,{data: LinearChatCreateRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createLinearChat>>, TError,{data: LinearChatCreateRequestDto}, TContext> => {

const mutationKey = ['createLinearChat'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLinearChat>>, {data: LinearChatCreateRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  createLinearChat(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateLinearChatMutationResult = NonNullable<Awaited<ReturnType<typeof createLinearChat>>>
    export type CreateLinearChatMutationBody = LinearChatCreateRequestDto
    export type CreateLinearChatMutationError = unknown

    /**
 * @summary Создать новый линейный чат
 */
export const useCreateLinearChat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLinearChat>>, TError,{data: LinearChatCreateRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLinearChat>>,
        TError,
        {data: LinearChatCreateRequestDto},
        TContext
      > => {

      const mutationOptions = getCreateLinearChatMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Создает новый линейный чат на основе существующего сообщения в текущем линейном чате и отправляет туда новый запрос пользователя
 * @summary Создай новый линейный чат из текущего и отправить в него сообщении к ИИ
 */
export const createNewLinearChatAndSendMessage = (
    branchCreateRequestDto: BranchCreateRequestDto,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<MessageCreateResponseDto>(
      {url: `/linear-chats/branch`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: branchCreateRequestDto, signal
    },
      );
    }
  


export const getCreateNewLinearChatAndSendMessageMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNewLinearChatAndSendMessage>>, TError,{data: BranchCreateRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createNewLinearChatAndSendMessage>>, TError,{data: BranchCreateRequestDto}, TContext> => {

const mutationKey = ['createNewLinearChatAndSendMessage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNewLinearChatAndSendMessage>>, {data: BranchCreateRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  createNewLinearChatAndSendMessage(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateNewLinearChatAndSendMessageMutationResult = NonNullable<Awaited<ReturnType<typeof createNewLinearChatAndSendMessage>>>
    export type CreateNewLinearChatAndSendMessageMutationBody = BranchCreateRequestDto
    export type CreateNewLinearChatAndSendMessageMutationError = unknown

    /**
 * @summary Создай новый линейный чат из текущего и отправить в него сообщении к ИИ
 */
export const useCreateNewLinearChatAndSendMessage = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNewLinearChatAndSendMessage>>, TError,{data: BranchCreateRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNewLinearChatAndSendMessage>>,
        TError,
        {data: BranchCreateRequestDto},
        TContext
      > => {

      const mutationOptions = getCreateNewLinearChatAndSendMessageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Возвращает список всех графовых чатов текущего пользователя
 * @summary Получить список всех графовых чатов пользователя
 */
export const getGraphChatsList = (
    
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<GraphChatShortResponseDto[]>(
      {url: `/graph-chats`, method: 'GET', signal
    },
      );
    }
  

export const getGetGraphChatsListQueryKey = () => {
    return [`/graph-chats`] as const;
    }

    
export const getGetGraphChatsListQueryOptions = <TData = Awaited<ReturnType<typeof getGraphChatsList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatsList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGraphChatsListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGraphChatsList>>> = ({ signal }) => getGraphChatsList(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGraphChatsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGraphChatsListQueryResult = NonNullable<Awaited<ReturnType<typeof getGraphChatsList>>>
export type GetGraphChatsListQueryError = unknown


export function useGetGraphChatsList<TData = Awaited<ReturnType<typeof getGraphChatsList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraphChatsList>>,
          TError,
          Awaited<ReturnType<typeof getGraphChatsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraphChatsList<TData = Awaited<ReturnType<typeof getGraphChatsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraphChatsList>>,
          TError,
          Awaited<ReturnType<typeof getGraphChatsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraphChatsList<TData = Awaited<ReturnType<typeof getGraphChatsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatsList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить список всех графовых чатов пользователя
 */

export function useGetGraphChatsList<TData = Awaited<ReturnType<typeof getGraphChatsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatsList>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGraphChatsListQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Создает новый графовый чат, его основную ветку и отправляет первое сообщение
 * @summary Создать новый графовый чат
 */
export const createGraphChat = (
    graphChatCreateRequestDto: GraphChatCreateRequestDto,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<GraphChatCreateResponseDto>(
      {url: `/graph-chats`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: graphChatCreateRequestDto, signal
    },
      );
    }
  


export const getCreateGraphChatMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGraphChat>>, TError,{data: GraphChatCreateRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createGraphChat>>, TError,{data: GraphChatCreateRequestDto}, TContext> => {

const mutationKey = ['createGraphChat'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGraphChat>>, {data: GraphChatCreateRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  createGraphChat(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGraphChatMutationResult = NonNullable<Awaited<ReturnType<typeof createGraphChat>>>
    export type CreateGraphChatMutationBody = GraphChatCreateRequestDto
    export type CreateGraphChatMutationError = unknown

    /**
 * @summary Создать новый графовый чат
 */
export const useCreateGraphChat = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGraphChat>>, TError,{data: GraphChatCreateRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGraphChat>>,
        TError,
        {data: GraphChatCreateRequestDto},
        TContext
      > => {

      const mutationOptions = getCreateGraphChatMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Проверяет секретный заголовок и на его основе регистрирует или возвращает данные пользователя
 * @summary Сервисный вход пользователя
 */
export const serviceLogin = (
    serviceLoginRequestDto: ServiceLoginRequestDto,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<UserIdResponseDto>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: serviceLoginRequestDto, signal
    },
      );
    }
  


export const getServiceLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceLogin>>, TError,{data: ServiceLoginRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof serviceLogin>>, TError,{data: ServiceLoginRequestDto}, TContext> => {

const mutationKey = ['serviceLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof serviceLogin>>, {data: ServiceLoginRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  serviceLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ServiceLoginMutationResult = NonNullable<Awaited<ReturnType<typeof serviceLogin>>>
    export type ServiceLoginMutationBody = ServiceLoginRequestDto
    export type ServiceLoginMutationError = unknown

    /**
 * @summary Сервисный вход пользователя
 */
export const useServiceLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof serviceLogin>>, TError,{data: ServiceLoginRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof serviceLogin>>,
        TError,
        {data: ServiceLoginRequestDto},
        TContext
      > => {

      const mutationOptions = getServiceLoginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Обновляет заголовок графового чата
 * @summary Переименовать графовый чат
 */
export const renameGraphChatById = (
    id: number,
    graphChatRenameRequestDto: GraphChatRenameRequestDto,
 ) => {
      
      
      return restApiAxiosClient<null>(
      {url: `/graph-chats/${id}/title`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: graphChatRenameRequestDto
    },
      );
    }
  


export const getRenameGraphChatByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameGraphChatById>>, TError,{id: number;data: GraphChatRenameRequestDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof renameGraphChatById>>, TError,{id: number;data: GraphChatRenameRequestDto}, TContext> => {

const mutationKey = ['renameGraphChatById'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameGraphChatById>>, {id: number;data: GraphChatRenameRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  renameGraphChatById(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RenameGraphChatByIdMutationResult = NonNullable<Awaited<ReturnType<typeof renameGraphChatById>>>
    export type RenameGraphChatByIdMutationBody = GraphChatRenameRequestDto
    export type RenameGraphChatByIdMutationError = unknown

    /**
 * @summary Переименовать графовый чат
 */
export const useRenameGraphChatById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameGraphChatById>>, TError,{id: number;data: GraphChatRenameRequestDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameGraphChatById>>,
        TError,
        {id: number;data: GraphChatRenameRequestDto},
        TContext
      > => {

      const mutationOptions = getRenameGraphChatByIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Возвращает информацию о текущем авторизованном пользователе
 * @summary Получить данные профиля пользователя
 */
export const getCurrentUser = (
    
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<UserDataResponseDto>(
      {url: `/user/me`, method: 'GET', signal
    },
      );
    }
  

export const getGetCurrentUserQueryKey = () => {
    return [`/user/me`] as const;
    }

    
export const getGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = unknown


export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить данные профиля пользователя
 */

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает сообщения для указанного линейного чата с поддержкой пагинации
 * @summary Получить сообщения линейного чата с пагинацией
 */
export const getMessagesByLinearChatId = (
    linearChatId: number,
    params: GetMessagesByLinearChatIdParams,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<MessagesPageResponseDto>(
      {url: `/messages/linear-chat/${linearChatId}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetMessagesByLinearChatIdQueryKey = (linearChatId?: number,
    params?: GetMessagesByLinearChatIdParams,) => {
    return [`/messages/linear-chat/${linearChatId}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetMessagesByLinearChatIdQueryOptions = <TData = Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError = unknown>(linearChatId: number,
    params: GetMessagesByLinearChatIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesByLinearChatIdQueryKey(linearChatId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessagesByLinearChatId>>> = ({ signal }) => getMessagesByLinearChatId(linearChatId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(linearChatId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesByLinearChatIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMessagesByLinearChatId>>>
export type GetMessagesByLinearChatIdQueryError = unknown


export function useGetMessagesByLinearChatId<TData = Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError = unknown>(
 linearChatId: number,
    params: GetMessagesByLinearChatIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesByLinearChatId>>,
          TError,
          Awaited<ReturnType<typeof getMessagesByLinearChatId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesByLinearChatId<TData = Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError = unknown>(
 linearChatId: number,
    params: GetMessagesByLinearChatIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesByLinearChatId>>,
          TError,
          Awaited<ReturnType<typeof getMessagesByLinearChatId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesByLinearChatId<TData = Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError = unknown>(
 linearChatId: number,
    params: GetMessagesByLinearChatIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить сообщения линейного чата с пагинацией
 */

export function useGetMessagesByLinearChatId<TData = Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError = unknown>(
 linearChatId: number,
    params: GetMessagesByLinearChatIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesByLinearChatId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesByLinearChatIdQueryOptions(linearChatId,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает полный список сообщений для указанного линейного чата
 * @summary Получить все сообщения линейного чата
 */
export const getAllMessagesByLinearChatId = (
    linearChatId: number,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<MessageResponseDto[]>(
      {url: `/messages/linear-chat/${linearChatId}/all`, method: 'GET', signal
    },
      );
    }
  

export const getGetAllMessagesByLinearChatIdQueryKey = (linearChatId?: number,) => {
    return [`/messages/linear-chat/${linearChatId}/all`] as const;
    }

    
export const getGetAllMessagesByLinearChatIdQueryOptions = <TData = Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError = unknown>(linearChatId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllMessagesByLinearChatIdQueryKey(linearChatId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>> = ({ signal }) => getAllMessagesByLinearChatId(linearChatId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(linearChatId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllMessagesByLinearChatIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>>
export type GetAllMessagesByLinearChatIdQueryError = unknown


export function useGetAllMessagesByLinearChatId<TData = Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError = unknown>(
 linearChatId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>,
          TError,
          Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllMessagesByLinearChatId<TData = Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError = unknown>(
 linearChatId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>,
          TError,
          Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllMessagesByLinearChatId<TData = Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError = unknown>(
 linearChatId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить все сообщения линейного чата
 */

export function useGetAllMessagesByLinearChatId<TData = Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError = unknown>(
 linearChatId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMessagesByLinearChatId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllMessagesByLinearChatIdQueryOptions(linearChatId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает полную структуру графа сообщений для указанного графового чата
 * @summary Получить полный граф сообщений
 */
export const getMessageGraphByGraphChatId = (
    graphChatId: number,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<MessageGraphDto>(
      {url: `/messages/graph-chat/${graphChatId}/full-graph`, method: 'GET', signal
    },
      );
    }
  

export const getGetMessageGraphByGraphChatIdQueryKey = (graphChatId?: number,) => {
    return [`/messages/graph-chat/${graphChatId}/full-graph`] as const;
    }

    
export const getGetMessageGraphByGraphChatIdQueryOptions = <TData = Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError = unknown>(graphChatId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessageGraphByGraphChatIdQueryKey(graphChatId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>> = ({ signal }) => getMessageGraphByGraphChatId(graphChatId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(graphChatId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessageGraphByGraphChatIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>>
export type GetMessageGraphByGraphChatIdQueryError = unknown


export function useGetMessageGraphByGraphChatId<TData = Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError = unknown>(
 graphChatId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>,
          TError,
          Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGraphByGraphChatId<TData = Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError = unknown>(
 graphChatId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>,
          TError,
          Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessageGraphByGraphChatId<TData = Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError = unknown>(
 graphChatId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить полный граф сообщений
 */

export function useGetMessageGraphByGraphChatId<TData = Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError = unknown>(
 graphChatId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessageGraphByGraphChatId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessageGraphByGraphChatIdQueryOptions(graphChatId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает полные данные линейного чата
 * @summary Получить данные линейного чата
 */
export const getLinearChatById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<LinearChatResponseDto>(
      {url: `/linear-chats/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetLinearChatByIdQueryKey = (id?: number,) => {
    return [`/linear-chats/${id}`] as const;
    }

    
export const getGetLinearChatByIdQueryOptions = <TData = Awaited<ReturnType<typeof getLinearChatById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinearChatById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLinearChatByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLinearChatById>>> = ({ signal }) => getLinearChatById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLinearChatById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLinearChatByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLinearChatById>>>
export type GetLinearChatByIdQueryError = unknown


export function useGetLinearChatById<TData = Awaited<ReturnType<typeof getLinearChatById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinearChatById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLinearChatById>>,
          TError,
          Awaited<ReturnType<typeof getLinearChatById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLinearChatById<TData = Awaited<ReturnType<typeof getLinearChatById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinearChatById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLinearChatById>>,
          TError,
          Awaited<ReturnType<typeof getLinearChatById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLinearChatById<TData = Awaited<ReturnType<typeof getLinearChatById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinearChatById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить данные линейного чата
 */

export function useGetLinearChatById<TData = Awaited<ReturnType<typeof getLinearChatById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLinearChatById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLinearChatByIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Удаляет линейный чат и все связанные с ним сообщения
 * @summary Удалить линейный чат
 */
export const deleteLinearChatById = (
    id: number,
 ) => {
      
      
      return restApiAxiosClient<null>(
      {url: `/linear-chats/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteLinearChatByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLinearChatById>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteLinearChatById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteLinearChatById'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLinearChatById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteLinearChatById(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteLinearChatByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLinearChatById>>>
    
    export type DeleteLinearChatByIdMutationError = unknown

    /**
 * @summary Удалить линейный чат
 */
export const useDeleteLinearChatById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLinearChatById>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLinearChatById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteLinearChatByIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Возвращает все данные графового чата
 * @summary Получить графовый чат
 */
export const getGraphChatById = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<GraphChatResponseDto>(
      {url: `/graph-chats/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getGetGraphChatByIdQueryKey = (id?: number,) => {
    return [`/graph-chats/${id}`] as const;
    }

    
export const getGetGraphChatByIdQueryOptions = <TData = Awaited<ReturnType<typeof getGraphChatById>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGraphChatByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGraphChatById>>> = ({ signal }) => getGraphChatById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGraphChatById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGraphChatByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getGraphChatById>>>
export type GetGraphChatByIdQueryError = unknown


export function useGetGraphChatById<TData = Awaited<ReturnType<typeof getGraphChatById>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraphChatById>>,
          TError,
          Awaited<ReturnType<typeof getGraphChatById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraphChatById<TData = Awaited<ReturnType<typeof getGraphChatById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGraphChatById>>,
          TError,
          Awaited<ReturnType<typeof getGraphChatById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGraphChatById<TData = Awaited<ReturnType<typeof getGraphChatById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить графовый чат
 */

export function useGetGraphChatById<TData = Awaited<ReturnType<typeof getGraphChatById>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGraphChatById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGraphChatByIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Полностью удаляет графовый чат, все вложенные линейные чаты и сообщения в них
 * @summary Удалить графовый чат
 */
export const deleteGraphChatById = (
    id: number,
 ) => {
      
      
      return restApiAxiosClient<null>(
      {url: `/graph-chats/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteGraphChatByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGraphChatById>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteGraphChatById>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteGraphChatById'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGraphChatById>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteGraphChatById(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteGraphChatByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGraphChatById>>>
    
    export type DeleteGraphChatByIdMutationError = unknown

    /**
 * @summary Удалить графовый чат
 */
export const useDeleteGraphChatById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGraphChatById>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteGraphChatById>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteGraphChatByIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Возвращает токен для авторизации в mqtt-брокере
 * @summary Получить токен для авторизации в mqtt-брокере
 */
export const getMqttAuthToken = (
    
 signal?: AbortSignal
) => {
      
      
      return restApiAxiosClient<MqttAuthTokenResponse>(
      {url: `/auth/mqtt/token`, method: 'GET', signal
    },
      );
    }
  

export const getGetMqttAuthTokenQueryKey = () => {
    return [`/auth/mqtt/token`] as const;
    }

    
export const getGetMqttAuthTokenQueryOptions = <TData = Awaited<ReturnType<typeof getMqttAuthToken>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMqttAuthToken>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMqttAuthTokenQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMqttAuthToken>>> = ({ signal }) => getMqttAuthToken(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMqttAuthToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMqttAuthTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getMqttAuthToken>>>
export type GetMqttAuthTokenQueryError = unknown


export function useGetMqttAuthToken<TData = Awaited<ReturnType<typeof getMqttAuthToken>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMqttAuthToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMqttAuthToken>>,
          TError,
          Awaited<ReturnType<typeof getMqttAuthToken>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMqttAuthToken<TData = Awaited<ReturnType<typeof getMqttAuthToken>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMqttAuthToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMqttAuthToken>>,
          TError,
          Awaited<ReturnType<typeof getMqttAuthToken>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMqttAuthToken<TData = Awaited<ReturnType<typeof getMqttAuthToken>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMqttAuthToken>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить токен для авторизации в mqtt-брокере
 */

export function useGetMqttAuthToken<TData = Awaited<ReturnType<typeof getMqttAuthToken>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMqttAuthToken>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMqttAuthTokenQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}


export const getSendMessageToExistingLinearChatResponseMock = (overrideResponse: Partial< MessageCreateResponseDto > = {}): MessageCreateResponseDto => ({userMessage: {id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, assistantMessage: {id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, ...overrideResponse})

export const getCreateLinearChatResponseMock = (overrideResponse: Partial< LinearChatResponseDto > = {}): LinearChatResponseDto => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), graphChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), parentLinearId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), attachedMessageId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), title: faker.string.alpha({length: {min: 10, max: 20}}), isLoading: faker.datatype.boolean(), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getCreateNewLinearChatAndSendMessageResponseMock = (overrideResponse: Partial< MessageCreateResponseDto > = {}): MessageCreateResponseDto => ({userMessage: {id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, assistantMessage: {id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, ...overrideResponse})

export const getGetGraphChatsListResponseMock = (): GraphChatShortResponseDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), title: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, isLoadingLinearChatsCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), rootLinearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined})})))

export const getCreateGraphChatResponseMock = (overrideResponse: Partial< GraphChatCreateResponseDto > = {}): GraphChatCreateResponseDto => ({graph: {id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), title: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, isLoadingLinearChatsCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), rootLinearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined})}, userMessage: {id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, assistantPlaceholder: {id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}, ...overrideResponse})

export const getServiceLoginResponseMock = (overrideResponse: Partial< UserIdResponseDto > = {}): UserIdResponseDto => ({userId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), ...overrideResponse})

export const getGetCurrentUserResponseMock = (overrideResponse: Partial< UserDataResponseDto > = {}): UserDataResponseDto => ({userName: faker.string.alpha({length: {min: 10, max: 20}}), userId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), ...overrideResponse})

export const getGetMessagesByLinearChatIdResponseMock = (overrideResponse: Partial< MessagesPageResponseDto > = {}): MessagesPageResponseDto => ({content: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})), totalElements: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), totalPages: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), number: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), size: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), first: faker.datatype.boolean(), last: faker.datatype.boolean(), ...overrideResponse})

export const getGetAllMessagesByLinearChatIdResponseMock = (): MessageResponseDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`})))

export const getGetMessageGraphByGraphChatIdResponseMock = (overrideResponse: Partial< MessageGraphDto > = {}): MessageGraphDto => ({graphChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), title: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, linearChats: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), title: faker.string.alpha({length: {min: 10, max: 20}}), parentLinearId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), attachedMessageId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), isLoading: faker.datatype.boolean(), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, messages: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), content: faker.string.alpha({length: {min: 10, max: 20}}), role: faker.helpers.arrayElement(['USER','ASSISTANT'] as const), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`}))})), ...overrideResponse})

export const getGetLinearChatByIdResponseMock = (overrideResponse: Partial< LinearChatResponseDto > = {}): LinearChatResponseDto => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), graphChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), parentLinearId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), attachedMessageId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), title: faker.string.alpha({length: {min: 10, max: 20}}), isLoading: faker.datatype.boolean(), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, ...overrideResponse})

export const getGetGraphChatByIdResponseMock = (overrideResponse: Partial< GraphChatResponseDto > = {}): GraphChatResponseDto => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), title: faker.string.alpha({length: {min: 10, max: 20}}), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, isLoadingLinearChatsCount: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), linearChatsTree: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), graphChatId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), parentLinearId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), attachedMessageId: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), title: faker.string.alpha({length: {min: 10, max: 20}}), isLoading: faker.datatype.boolean(), createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`, children: []})), ...overrideResponse})

export const getGetMqttAuthTokenResponseMock = (overrideResponse: Partial< MqttAuthTokenResponse > = {}): MqttAuthTokenResponse => ({token: faker.string.alpha({length: {min: 10, max: 20}}), expiresAt: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), ...overrideResponse})


export const getSendMessageToExistingLinearChatMockHandler = (overrideResponse?: MessageCreateResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MessageCreateResponseDto> | MessageCreateResponseDto)) => {
  return http.post('*/messages', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSendMessageToExistingLinearChatResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCreateLinearChatMockHandler = (overrideResponse?: LinearChatResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<LinearChatResponseDto> | LinearChatResponseDto)) => {
  return http.post('*/linear-chats', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateLinearChatResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCreateNewLinearChatAndSendMessageMockHandler = (overrideResponse?: MessageCreateResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<MessageCreateResponseDto> | MessageCreateResponseDto)) => {
  return http.post('*/linear-chats/branch', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateNewLinearChatAndSendMessageResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetGraphChatsListMockHandler = (overrideResponse?: GraphChatShortResponseDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GraphChatShortResponseDto[]> | GraphChatShortResponseDto[])) => {
  return http.get('*/graph-chats', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetGraphChatsListResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getCreateGraphChatMockHandler = (overrideResponse?: GraphChatCreateResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<GraphChatCreateResponseDto> | GraphChatCreateResponseDto)) => {
  return http.post('*/graph-chats', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateGraphChatResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getServiceLoginMockHandler = (overrideResponse?: UserIdResponseDto | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<UserIdResponseDto> | UserIdResponseDto)) => {
  return http.post('*/auth/login', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getServiceLoginResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getRenameGraphChatByIdMockHandler = (overrideResponse?: null | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<null> | null)) => {
  return http.patch('*/graph-chats/:id/title', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getGetCurrentUserMockHandler = (overrideResponse?: UserDataResponseDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserDataResponseDto> | UserDataResponseDto)) => {
  return http.get('*/user/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCurrentUserResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetMessagesByLinearChatIdMockHandler = (overrideResponse?: MessagesPageResponseDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MessagesPageResponseDto> | MessagesPageResponseDto)) => {
  return http.get('*/messages/linear-chat/:linearChatId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMessagesByLinearChatIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetAllMessagesByLinearChatIdMockHandler = (overrideResponse?: MessageResponseDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MessageResponseDto[]> | MessageResponseDto[])) => {
  return http.get('*/messages/linear-chat/:linearChatId/all', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllMessagesByLinearChatIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetMessageGraphByGraphChatIdMockHandler = (overrideResponse?: MessageGraphDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MessageGraphDto> | MessageGraphDto)) => {
  return http.get('*/messages/graph-chat/:graphChatId/full-graph', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMessageGraphByGraphChatIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetLinearChatByIdMockHandler = (overrideResponse?: LinearChatResponseDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<LinearChatResponseDto> | LinearChatResponseDto)) => {
  return http.get('*/linear-chats/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetLinearChatByIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getDeleteLinearChatByIdMockHandler = (overrideResponse?: null | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<null> | null)) => {
  return http.delete('*/linear-chats/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getGetGraphChatByIdMockHandler = (overrideResponse?: GraphChatResponseDto | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GraphChatResponseDto> | GraphChatResponseDto)) => {
  return http.get('*/graph-chats/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetGraphChatByIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getDeleteGraphChatByIdMockHandler = (overrideResponse?: null | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<null> | null)) => {
  return http.delete('*/graph-chats/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getGetMqttAuthTokenMockHandler = (overrideResponse?: MqttAuthTokenResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MqttAuthTokenResponse> | MqttAuthTokenResponse)) => {
  return http.get('*/auth/mqtt/token', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMqttAuthTokenResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getOpenAPIDefinitionMock = () => [
  getSendMessageToExistingLinearChatMockHandler(),
  getCreateLinearChatMockHandler(),
  getCreateNewLinearChatAndSendMessageMockHandler(),
  getGetGraphChatsListMockHandler(),
  getCreateGraphChatMockHandler(),
  getServiceLoginMockHandler(),
  getRenameGraphChatByIdMockHandler(),
  getGetCurrentUserMockHandler(),
  getGetMessagesByLinearChatIdMockHandler(),
  getGetAllMessagesByLinearChatIdMockHandler(),
  getGetMessageGraphByGraphChatIdMockHandler(),
  getGetLinearChatByIdMockHandler(),
  getDeleteLinearChatByIdMockHandler(),
  getGetGraphChatByIdMockHandler(),
  getDeleteGraphChatByIdMockHandler(),
  getGetMqttAuthTokenMockHandler()
]
