/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Pageable } from './pageable';

export type GetMessagesByLinearChatIdParams = {
pageable: Pageable;
};
