/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LinearChatTreeNode } from './linearChatTreeNode';

export interface GraphChatResponseDto {
  id: number;
  title: string;
  createdAt: string;
  isLoadingLinearChatsCount: number;
  linearChatsTree: LinearChatTreeNode[];
}
