/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface GraphChatShortResponseDto {
  id: number;
  title: string;
  createdAt: string;
  isLoadingLinearChatsCount: number;
  rootLinearChatId: number;
}
