/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GraphChatShortResponseDto } from './graphChatShortResponseDto';
import type { MessageResponseDto } from './messageResponseDto';

export interface GraphChatCreateResponseDto {
  graph: GraphChatShortResponseDto;
  userMessage: MessageResponseDto;
  assistantPlaceholder: MessageResponseDto;
}
