/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MessageNodeDto } from './messageNodeDto';

export interface LinearChatNodeDto {
  id: number;
  title: string;
  parentLinearId: number;
  attachedMessageId: number;
  isLoading: boolean;
  createdAt: string;
  messages: MessageNodeDto[];
}
