/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LinearChatCreateRequestDto {
  graphChatId: number;
  parentLinearId: number;
  attachedMessageId: number;
  title: string;
  isLoading: boolean;
}
