/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MessageCreateRequestDtoRole } from './messageCreateRequestDtoRole';

export interface MessageCreateRequestDto {
  linearChatId: number;
  content: string;
  role: MessageCreateRequestDtoRole;
}
