/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LinearChatNodeDto } from './linearChatNodeDto';

export interface MessageGraphDto {
  graphChatId: number;
  title: string;
  createdAt: string;
  linearChats: LinearChatNodeDto[];
}
