/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MessageNodeDtoRole = typeof MessageNodeDtoRole[keyof typeof MessageNodeDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageNodeDtoRole = {
  USER: 'USER',
  ASSISTANT: 'ASSISTANT',
} as const;
