/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MessageNodeDtoRole } from './messageNodeDtoRole';

export interface MessageNodeDto {
  id: number;
  content: string;
  role: MessageNodeDtoRole;
  createdAt: string;
  updatedAt: string;
}
