/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MessageGraphNodeDtoRole } from './messageGraphNodeDtoRole';

export interface MessageGraphNodeDto {
  id: number;
  linearChatId: number;
  content: string;
  role: MessageGraphNodeDtoRole;
  createdAt: string;
  updatedAt: string;
}
