/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MessageGraphNodeDtoRole = typeof MessageGraphNodeDtoRole[keyof typeof MessageGraphNodeDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageGraphNodeDtoRole = {
  USER: 'USER',
  ASSISTANT: 'ASSISTANT',
} as const;
