/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Pageable {
  /** @minimum 0 */
  page: number;
  /** @minimum 1 */
  size: number;
  sort: string[];
}
